NEWLINE: str = '\n'
SPACE: str = ' '
NEW_IP: str = '0.0.0.0'
FILE_APPEND: str = 'a'
FILE_READ: str = 'r'
FILE_WRITE: str = 'w'
LINUX: str = "Linux"
WINDOWS: str = "Windows"
WIDTH: int = 600
HEIGHT: int = 400